# fly.toml app configuration file generated for lexionline-backend on 2025-09-01T15:05:26+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lexionline-backend'
primary_region = 'nrt'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = '8080'
  NODE_ENV = 'production'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['colyseus-app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
