-- AlterTable
ALTER TABLE "User" ADD COLUMN "playCount_2p" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "User" ADD COLUMN "wins_2p" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "User" ADD COLUMN "second_2p" INTEGER NOT NULL DEFAULT 0;
